import Express from "express";
import controller from "./controller";
import auth from "../../../../helper/auth";
import upload from "../../../../helper/uploadHandler";
import cron from "./cron";

export default Express.Router()

  .post("/login", controller.login)
  .post("/forgotPassword", controller.forgotPassword)
  .patch("/verifyOTP", controller.verifyOTP)
  .post("/resendOtp", controller.resendOtp)
  .post("/resetPassword", controller.resetPassword)

  .use(auth.verifyToken)
  .get("/getProfile", controller.getProfile)
  .patch("/changePassword", controller.changePassword)
  .get("/userList", controller.userList)
  .get("/mostWonUser", controller.mostWonUser)
  .get("/mostWithdrawUser", controller.mostWithdrawUser)
  .get("/viewUser", controller.viewUser)
  .get("/updateBalance", controller.updateBalance)
  .put("/activeSelectedUser", controller.activeSelectedUser)
  .put("/activeBlockUser", controller.activeBlockUser)
  .put("/activeAllUser", controller.activeAllUser)
  .put("/editUserProfile", controller.editUserProfile)
  .delete("/deleteUser", controller.deleteUser)
  .get("/dashBoard", controller.dashBoard)
  .get("/userDashboard", controller.userdashBoard)
  .get("/graphDW", controller.graphDW)
  .post("/addSubAdmin", controller.addSubAdmin)
  .get("/listSubAdmin", controller.listSubAdmin)
  .put("/blockUnblockSubAdmin", controller.blockUnblockSubAdmin)
  .put("/replyContactUs", controller.replyContactUs)
  .delete("/deleteSubAdmin", controller.deleteSubAdmin)
  .delete("/deletedb", controller.deletedb)
  .delete("/updateLockedAmount", controller.updateLockedAmount)
  .get("/graphForUser", controller.graphForUser)
  .get("/allgameHistory", controller.GameHistory)
  .get("/graphGameHistory", controller.graphGameHistory)
  .get("/graphUserGameHistory", controller.graphUserGameHistory)
  .get("/graphGameScoreAll", controller.graphGameScoreAll)
  .get("/userRegistration", controller.userRegistration)
  .get("/userReferredList", controller.userReferredList)
  .get("/getUserActivity", controller.getUserActivity)
  .get("/getAdminActivity", controller.getAdminActivity)
  .get("/getUserGameHistory", controller.getUserGameHistory)
  .get("/approvedEmail", controller.approvedEmail)
  .get("/listBlockedUserName", controller.listBlockedUserName)
  .put("/editBlockedUserName", controller.editBlockedUserName)
  .delete("/deleteBlockedUserName", controller.deleteBlockedUserName)
  .delete("/deleteSelectedUserName", controller.deleteSelectedUserName)
  .get("/dashboardV1", controller.dashboardV1)
  .put("/editAdminWallet", controller.editAdminWallet)
  .use(upload.uploadFile)
  .put("/editProfile", controller.editProfile)
  .put("/editProfileSubAdmin", controller.editProfileSubAdmin)
  .get("/settings", controller.getAdminSettings)
  .get("/allHistories", controller.AlluserHistories)
  .put("/settings", controller.updateAdminSettings);
